server:
  port: 8081
prpc:
#当前服务发布端口
  serverPort: 8888
#注册中心有Nacos和Zookeeper
#  registry: "nacos"
#  registryAddress: "localhost:8848"
  registry: "zookeeper"
  registryAddress: "localhost:2181"
  zookeeperRootPath: "prpc"
  zookeeperRetryBaseTime: 1000
  zookeeperRetryTimes: 3
  #序列化算法JDK，GSON，FastJSON，Kryo，Hessian2，Protostuff
  serializerAlgorithm: "JDK"