#nacos
server:
  port: 8081
prpc:
  nacosAddress: "localhost:8848"
  serverPort: 8888
  serializerAlgorithm: "JDK"
  registry: "nacos"

#zookeeper
#server:
#  port: 8081
#prpc:
#  serverPort: 8888
#  serializerAlgorithm: "JDK"
#  registry: "zookeeper"
#  zookeeperAddress: "localhost:2181"
#  zookeeperRootPath: "prpc"
#  zookeeperRetryBaseTime: 1000
#  zookeeperRetryTimes: 3