server:
  port: 8000
prpc:
#注册中心有Nacos和Zookeeper
#  registry: "nacos"
#  registryAddress: "localhost:8848"
  registry: "zookeeper"
  registryAddress: "localhost:2181"
  zookeeperRootPath: "prpc"
  zookeeperRetryBaseTime: 1000
  zookeeperRetryTimes: 3

#通用的超时设置
  reConnectNumber: 5
  timeOut: 3000

#序列化算法JDK，GSON，FastJSON，Kryo，Hessian2，Protostuff
  serializerAlgorithm: "JDK"
#负载均衡算法，random，polling，hash，consistentHash
  loadBalanceAlgorithm: "consistentHash"
#一致性哈希环虚拟节点数
  virtualNodeNum: 100
#压缩算法，目前只有GZIP
  compressAlgorithm: "GZIP"
#代理实现，JDK和CGLib
  proxy: "cglib"