server:
  port: 8000

prpc:
  nacosAddress: "localhost:8848"
  reConnectNumber: 5
  serializerAlgorithm: "kryo"
  timeOut: 3000
  loadBalanceAlgorithm: "consistentHash"
  virtualNodeNum: 100
  compressAlgorithm: "GZIP"
  proxy: "cglib"
  registry: "nacos"
#  zookeeperAddress: "localhost:2181"
#  zookeeperRootPath: "prpc"
#  zookeeperRetryBaseTime: 1000
#  zookeeperRetryTimes: 3

spring:
  application:
    name: prpc
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848