server:
  port: 8000
prpc:
  nacosAddress: "localhost:8848"
  reConnectNumber: 5
  serializerAlgorithm: "kryo"
  timeOut: 3000
  loadBalanceAlgorithm: "consistentHash"
  virtualNodeNum: 100
  compressAlgorithm: "GZIP"
  proxy: "cglib"
spring:
  cloud:
    nacos:
      discovery:
        service: "aaa"