#nacos配置
server:
  port: 8000

prpc:
  nacosAddress: "localhost:8848"
  reConnectNumber: 5
  serializerAlgorithm: "kryo"
  timeOut: 3000
  loadBalanceAlgorithm: "consistentHash"
  virtualNodeNum: 100
  compressAlgorithm: "GZIP"
  proxy: "cglib"
  registry: "nacos"

##zookeeper配置
#server:
#  port: 8000
#
#prpc:
#  reConnectNumber: 5
#  serializerAlgorithm: "kryo"
#  timeOut: 3000
#  loadBalanceAlgorithm: "consistentHash"
#  virtualNodeNum: 100
#  compressAlgorithm: "GZIP"
#  proxy: "cglib"
#  registry: "zookeeper"
#  zookeeperAddress: "localhost:2181"
#  zookeeperRootPath: "prpc"
#  zookeeperRetryBaseTime: 1000
#  zookeeperRetryTimes: 3